In [15]:
#vamos utilizar um modelo sequencial - rede neural - do keras
from tensorflow.keras.models import Sequential
#vamos importar o Dense para ser o modelo de ativação entre camadas
from tensorflow.keras.layers import Dense

#instanciar o modelo
rede = Sequential()

#Criar a camada de entrada
rede.add(Dense(109,activation='relu',input_shape=(109,)))

#Criando a camada oculta (montada automaticamente pela rede neural)
rede.add(Dense(8,activation='relu'))

#Criando a camada de saída (responde a classificação pela rede neural)
rede.add(Dense(2,activation='relu'))

#compilar a rede neural
rede.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
import numpy as np #módulo para trabalhar com números
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd

dataset = pd.read_excel("dataset-covid_einstein-TRATADO.xlsx")
colunas = dataset.columns.tolist()
colunasTratadas = colunas[2:3] + colunas[4:]

caracteristicas = dataset[colunasTratadas]
classes = dataset.iloc[:, 3].values



carac_treino,carac_teste, classes_treino, classes_teste = train_test_split(caracteristicas,classes,test_size=0.25,random_state=5)

#Padronizar os valores do treino
padrao = StandardScaler().fit(carac_treino)
carac_treino = padrao.transform(carac_treino)
carac_teste = padrao.transform(carac_teste)


In [17]:
rede.fit(carac_treino,classes_treino,epochs=10,batch_size=1,verbose=1)

Epoch 1/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.5105 - accuracy: 0.8592
Epoch 2/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.4533 - accuracy: 0.9059
Epoch 3/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.4080 - accuracy: 0.9086
Epoch 4/10
4233/4233 [==============================] - 5s 1ms/step - loss: 1.5317 - accuracy: 0.8993
Epoch 5/10
4233/4233 [==============================] - 7s 2ms/step - loss: 1.5174 - accuracy: 0.9010
Epoch 6/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.3971 - accuracy: 0.9078
Epoch 7/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.4512 - accuracy: 0.9048
Epoch 8/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.6142 - accuracy: 0.8953
Epoch 9/10
4233/4233 [==============================] - 6s 1ms/step - loss: 1.5133 - accuracy: 0.9007
Epoch 10/10
4233/4233 [==============================] - 5s 1ms/step - loss: 1.502

In [18]:
#avaliando a rede treinada com os dados de teste
resultados = rede.evaluate(carac_teste,classes_teste)

print('%s: %.2f%%' %(rede.metrics_names[1],resultados[1]*100))



45/45 [==============================] - 0s 853us/step - loss: 1.4331 - accuracy: 0.9064
accuracy: 90.64%


In [19]:
import numpy as np
teste = np.reshape(carac_teste[71], (1,109))
tipo = rede.predict(teste)
print(tipo)

[[0. 0.]]


In [20]:
indice = 0
for numero in classes_teste:
    if numero == 1:
        print("existe", indice)
    indice += 1

existe 4
existe 5
existe 8
existe 17
existe 25
existe 30
existe 36
existe 40
existe 43
existe 64
existe 65
existe 69
existe 70
existe 83
existe 99
existe 109
existe 120
existe 127
existe 134
existe 135
existe 160
existe 184
existe 189
existe 191
existe 196
existe 206
existe 211
existe 221
existe 227
existe 247
existe 251
existe 255
existe 260
existe 269
existe 272
existe 278
existe 289
existe 301
existe 338
existe 340
existe 346
existe 348
existe 368
existe 387
existe 396
existe 399
existe 421
existe 425
existe 434
existe 436
existe 470
existe 475
existe 479
existe 503
existe 508
existe 516
existe 534
existe 544
existe 552
existe 565
existe 571
existe 573
existe 580
existe 586
existe 600
existe 621
existe 624
existe 629
existe 656
existe 660
existe 662
existe 699
existe 711
existe 724
existe 726
existe 732
existe 735
existe 741
existe 753
existe 757
existe 769
existe 780
existe 788
existe 836
existe 842
existe 850
existe 888
existe 892
existe 893
existe 895
existe 903
existe 909
existe

In [21]:
for numero in classes_teste:
    teste = np.reshape(carac_teste[numero], (1,109))
    tipo = rede.predict(teste)
    print(tipo)

[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
[[0. 0.]]
